name: deploy-pages

on:
  push:
    branches: [main]

permissions:
  contents: write                # gh-pages 푸시 권한

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    defaults:                    # ↓ 모든 run 스텝에 기본 적용
      run:
        working-directory: frontend/ad-scrap

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build      # dist 생성

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/ad-scrap/dist   # ← 빌드 결과 경로
          clean: true
