name: deploy-pages

on:
  push:
    branches: [main]

permissions:
  contents: write            # gh-pages 브랜치 푸시 권한

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Node 먼저
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2) pnpm 설치
      - uses: pnpm/action-setup@v4       # ← v4 필수
        with:
          version: 8                     # 로컬과 동일 버전

      # 3) 의존성 설치
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4) 빌드
      - name: Build
        run: pnpm run build              # dist 폴더 생성

      # 5) GitHub Pages 배포
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist                   # vite outDir 과 동일
          clean: true
